### ISSUE TITLE
Freeze i dont dont know why 

### ISSUE THREAD

**Issue by Lordlorio** [White9shadow/God-Speed-Mode#3]
Maybe because I have too app in background or I have Atteind the limit of cache ram 3.25 please fix it I love your module

**Comment by White9shadow** [comment]
You tried letest GSM?

**Comment by Lordlorio** [comment]
> You tried letest GSM?

Sorry what ?

**Comment by Lordlorio** [comment]
> You tried letest GSM?

You talking the last version on GitHub yes

**Comment by White9shadow** [comment]
Not on github,on pling or you can find it on telegram channel @godTspeed @godspeedmode here.

**Comment by Lordlorio** [comment]
> Not on github,on pling or you can find it on telegram channel @godTspeed @godspeedmode here.

You talking about the last on the May 29 yes but I don't why the ram is not more Free

**Comment by darker16** [comment]
> ကျွန်ုပ်တွင် နောက်ခံတွင် အက်ပ်များ များလွန်းသောကြောင့် ဖြစ်နိုင်သည် သို့မဟုတ် ကျွန်ုပ်တွင် cache ram 3.25 ၏ ကန့်သတ်ချက်ကို လိုက်နာပြီး ကျေးဇူးပြု၍ ပြုပြင်ပါ ကျွန်ုပ်သည် သင်၏ module ကို နှစ်သက်ပါသည်။
