### ISSUE TITLE
Make it open source, you're violating the GNU policies.

### ISSUE THREAD

**Issue by forsaken-heart24** [White9shadow/God-Speed-Mode#5]

**Comment by White9shadow** [comment]
As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.

**Comment by forsaken-heart24** [comment]
> As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.

oh, that's nice

**Comment by White9shadow** [comment]
> > As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.
> 
> oh, that's nice

 check this https://t.me/rem01gayming/203❤️

**Comment by forsaken-heart24** [comment]
> > > As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.
> > 
> > 
> > oh, that's nice
> 
> check [this](https://t.me/rem01gayming/203)❤️

tbh that kid went too far and you should stop fighting with that kid man🤣

**Comment by White9shadow** [comment]
> > > > As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.
> > > 
> > > 
> > > oh, that's nice
> > 
> > 
> > check [this](https://t.me/rem01gayming/203)❤️
> 
> tbh that kid went too far and you should stop fighting with that kid man🤣

What kind of fight are you talking about. i dont know about anything 🫣

**Comment by forsaken-heart24** [comment]
> > > > > As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.
> > > > 
> > > > 
> > > > oh, that's nice
> > > 
> > > 
> > > check [this](https://t.me/rem01gayming/203)❤️
> > 
> > 
> > tbh that kid went too far and you should stop fighting with that kid man🤣
> 
> What kind of fight are you talking about. i dont know about anything 🫣

i thought it's an fight lol🤣

**Comment by White9shadow** [comment]
> > > > > > As mentioned on my Telegram, I will be updating the license terms or transitioning the project to open source gradually. There's no need to open further issues regarding this matter, as it is already in progress.
> > > > > 
> > > > > 
> > > > > oh, that's nice
> > > > 
> > > > 
> > > > check [this](https://t.me/rem01gayming/203)❤️
> > > 
> > > 
> > > tbh that kid went too far and you should stop fighting with that kid man🤣
> > 
> > 
> > What kind of fight are you talking about. i dont know about anything 🫣
> 
> i thought it's an fight lol🤣

no just enjoy your self in my account .
also dont forget to give stars and follow and share ☠️
